export type Faculty =
  | "Engineering & Technology"
  | "Health Sciences"
  | "Business & Economics"
  | "Natural Sciences"
  | "Law"
  | "Agriculture & Veterinary"
  | "Social Sciences & Humanities";

export interface Department {
  id: string;
  name: string;
  faculty: Faculty;
  icon: string;
  color: string;           // Tailwind gradient classes
  bgAccent: string;        // subtle bg tint
  examCount: number;
  studentCount: number;
  passRate: number;
  avgScore: number;
  difficulty: "Easy" | "Medium" | "Hard";
  topUniversities: string[];
  description: string;
  tags: string[];
}

export const UNIVERSITIES = [
  "All Universities",
  "Addis Ababa University",
  "Jimma University",
  "Hawassa University",
  "Mekelle University",
  "Bahir Dar University",
  "Haramaya University",
  "Arba Minch University",
  "Gondar University",
  "Adama Science & Technology",
  "Dire Dawa University",
];

export const EXAM_YEARS = ["All Years", "2024", "2023", "2022", "2021", "2020", "2019", "2018"];

export const DEPARTMENTS: Department[] = [
  // ── Engineering & Technology ──────────────────────────────────────────────
  {
    id: "cs",
    name: "Computer Science",
    faculty: "Engineering & Technology",
    icon: "💻",
    color: "from-violet-500 to-indigo-600",
    bgAccent: "bg-violet-500/10",
    examCount: 24,
    studentCount: 4820,
    passRate: 78,
    avgScore: 72,
    difficulty: "Hard",
    topUniversities: ["AAU", "ASTU", "BDU"],
    description: "Algorithms, data structures, OS, networks, databases and software engineering.",
    tags: ["Programming", "Algorithms", "Networks", "Databases"],
  },
  {
    id: "se",
    name: "Software Engineering",
    faculty: "Engineering & Technology",
    icon: "⚙️",
    color: "from-blue-500 to-cyan-600",
    bgAccent: "bg-blue-500/10",
    examCount: 20,
    studentCount: 3600,
    passRate: 75,
    avgScore: 70,
    difficulty: "Hard",
    topUniversities: ["AAU", "ASTU", "JU"],
    description: "Software design, development methodologies, testing and project management.",
    tags: ["Design Patterns", "Testing", "Agile", "Architecture"],
  },
  {
    id: "it",
    name: "Information Technology",
    faculty: "Engineering & Technology",
    icon: "🖥️",
    color: "from-sky-500 to-blue-600",
    bgAccent: "bg-sky-500/10",
    examCount: 18,
    studentCount: 3200,
    passRate: 80,
    avgScore: 74,
    difficulty: "Medium",
    topUniversities: ["AAU", "HU", "MU"],
    description: "IT infrastructure, systems analysis, networking and information security.",
    tags: ["Networking", "Security", "Systems", "IT Management"],
  },
  {
    id: "civil",
    name: "Civil Engineering",
    faculty: "Engineering & Technology",
    icon: "🏗️",
    color: "from-orange-500 to-amber-600",
    bgAccent: "bg-orange-500/10",
    examCount: 26,
    studentCount: 5100,
    passRate: 73,
    avgScore: 68,
    difficulty: "Hard",
    topUniversities: ["AAU", "JU", "BDU"],
    description: "Structural analysis, hydraulics, geotechnics, transportation and surveying.",
    tags: ["Structures", "Hydraulics", "Geotechnics", "Transportation"],
  },
  {
    id: "electrical",
    name: "Electrical Engineering",
    faculty: "Engineering & Technology",
    icon: "⚡",
    color: "from-yellow-500 to-orange-500",
    bgAccent: "bg-yellow-500/10",
    examCount: 28,
    studentCount: 3950,
    passRate: 75,
    avgScore: 70,
    difficulty: "Hard",
    topUniversities: ["AAU", "ASTU", "MU"],
    description: "Circuit theory, power systems, electronics, signals and control systems.",
    tags: ["Power Systems", "Electronics", "Control", "Signals"],
  },
  {
    id: "mechanical",
    name: "Mechanical Engineering",
    faculty: "Engineering & Technology",
    icon: "🔧",
    color: "from-slate-500 to-gray-600",
    bgAccent: "bg-slate-500/10",
    examCount: 22,
    studentCount: 3400,
    passRate: 72,
    avgScore: 67,
    difficulty: "Hard",
    topUniversities: ["AAU", "ASTU", "BDU"],
    description: "Thermodynamics, fluid mechanics, machine design and manufacturing.",
    tags: ["Thermodynamics", "Fluid Mechanics", "Machine Design"],
  },
  {
    id: "arch",
    name: "Architecture",
    faculty: "Engineering & Technology",
    icon: "🏛️",
    color: "from-purple-500 to-violet-600",
    bgAccent: "bg-purple-500/10",
    examCount: 18,
    studentCount: 2100,
    passRate: 70,
    avgScore: 66,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "HU"],
    description: "Architectural design, urban planning, building technology and history.",
    tags: ["Design", "Urban Planning", "Building Tech", "History"],
  },

  // ── Health Sciences ───────────────────────────────────────────────────────
  {
    id: "med",
    name: "Medicine",
    faculty: "Health Sciences",
    icon: "🏥",
    color: "from-rose-500 to-pink-600",
    bgAccent: "bg-rose-500/10",
    examCount: 32,
    studentCount: 6100,
    passRate: 72,
    avgScore: 68,
    difficulty: "Hard",
    topUniversities: ["AAU", "JU", "GU"],
    description: "Clinical sciences, pathology, pharmacology, surgery and internal medicine.",
    tags: ["Clinical", "Pathology", "Pharmacology", "Surgery"],
  },
  {
    id: "nursing",
    name: "Nursing",
    faculty: "Health Sciences",
    icon: "💊",
    color: "from-pink-500 to-rose-500",
    bgAccent: "bg-pink-500/10",
    examCount: 22,
    studentCount: 8200,
    passRate: 76,
    avgScore: 72,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "HU", "GU"],
    description: "Nursing care, medical-surgical nursing, maternal & child health.",
    tags: ["Patient Care", "Med-Surgical", "Community Health"],
  },
  {
    id: "midwifery",
    name: "Midwifery",
    faculty: "Health Sciences",
    icon: "👶",
    color: "from-fuchsia-500 to-pink-500",
    bgAccent: "bg-fuchsia-500/10",
    examCount: 18,
    studentCount: 5400,
    passRate: 77,
    avgScore: 73,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "BDU"],
    description: "Antenatal care, delivery, postnatal care and reproductive health.",
    tags: ["Antenatal", "Delivery", "Reproductive Health"],
  },
  {
    id: "pubhealth",
    name: "Public Health",
    faculty: "Health Sciences",
    icon: "🌡️",
    color: "from-teal-500 to-emerald-600",
    bgAccent: "bg-teal-500/10",
    examCount: 20,
    studentCount: 4900,
    passRate: 79,
    avgScore: 74,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "HU"],
    description: "Epidemiology, biostatistics, health policy, disease prevention.",
    tags: ["Epidemiology", "Biostatistics", "Health Policy"],
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    faculty: "Health Sciences",
    icon: "💉",
    color: "from-emerald-500 to-teal-500",
    bgAccent: "bg-emerald-500/10",
    examCount: 24,
    studentCount: 3800,
    passRate: 74,
    avgScore: 69,
    difficulty: "Hard",
    topUniversities: ["AAU", "JU", "GU"],
    description: "Pharmacology, pharmaceutical chemistry, clinical pharmacy and drug dispensing.",
    tags: ["Pharmacology", "Drug Chemistry", "Clinical Pharmacy"],
  },

  // ── Business & Economics ──────────────────────────────────────────────────
  {
    id: "econ",
    name: "Economics",
    faculty: "Business & Economics",
    icon: "📈",
    color: "from-green-500 to-emerald-600",
    bgAccent: "bg-green-500/10",
    examCount: 22,
    studentCount: 6800,
    passRate: 80,
    avgScore: 75,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "MU"],
    description: "Microeconomics, macroeconomics, econometrics and development economics.",
    tags: ["Microeconomics", "Macroeconomics", "Econometrics"],
  },
  {
    id: "accounting",
    name: "Accounting & Finance",
    faculty: "Business & Economics",
    icon: "📊",
    color: "from-blue-500 to-indigo-600",
    bgAccent: "bg-blue-500/10",
    examCount: 22,
    studentCount: 7300,
    passRate: 82,
    avgScore: 77,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "BDU"],
    description: "Financial accounting, managerial accounting, auditing and taxation.",
    tags: ["Financial Accounting", "Audit", "Taxation", "Finance"],
  },
  {
    id: "management",
    name: "Management",
    faculty: "Business & Economics",
    icon: "🤝",
    color: "from-indigo-500 to-purple-600",
    bgAccent: "bg-indigo-500/10",
    examCount: 20,
    studentCount: 8900,
    passRate: 83,
    avgScore: 78,
    difficulty: "Easy",
    topUniversities: ["AAU", "JU", "HU", "BDU"],
    description: "Organizational behavior, HRM, strategic management and entrepreneurship.",
    tags: ["HRM", "Strategy", "Leadership", "Marketing"],
  },

  // ── Law ───────────────────────────────────────────────────────────────────
  {
    id: "law",
    name: "Law",
    faculty: "Law",
    icon: "⚖️",
    color: "from-amber-500 to-yellow-600",
    bgAccent: "bg-amber-500/10",
    examCount: 20,
    studentCount: 5200,
    passRate: 68,
    avgScore: 63,
    difficulty: "Hard",
    topUniversities: ["AAU", "MU", "HU"],
    description: "Constitutional law, civil law, criminal law, commercial and international law.",
    tags: ["Constitutional", "Civil Law", "Criminal Law", "International"],
  },

  // ── Natural Sciences ──────────────────────────────────────────────────────
  {
    id: "biology",
    name: "Biology",
    faculty: "Natural Sciences",
    icon: "🧬",
    color: "from-lime-500 to-green-600",
    bgAccent: "bg-lime-500/10",
    examCount: 16,
    studentCount: 3200,
    passRate: 76,
    avgScore: 71,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "HU"],
    description: "Cell biology, genetics, ecology, zoology and botany.",
    tags: ["Genetics", "Ecology", "Biochemistry", "Botany"],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    faculty: "Natural Sciences",
    icon: "⚗️",
    color: "from-cyan-500 to-blue-600",
    bgAccent: "bg-cyan-500/10",
    examCount: 16,
    studentCount: 2800,
    passRate: 74,
    avgScore: 69,
    difficulty: "Hard",
    topUniversities: ["AAU", "JU", "MU"],
    description: "Organic, inorganic, physical and analytical chemistry.",
    tags: ["Organic", "Inorganic", "Physical Chemistry", "Analytical"],
  },
  {
    id: "math",
    name: "Mathematics",
    faculty: "Natural Sciences",
    icon: "🔢",
    color: "from-violet-500 to-purple-600",
    bgAccent: "bg-violet-500/10",
    examCount: 18,
    studentCount: 3000,
    passRate: 71,
    avgScore: 66,
    difficulty: "Hard",
    topUniversities: ["AAU", "MU", "BDU"],
    description: "Calculus, linear algebra, differential equations and real analysis.",
    tags: ["Calculus", "Linear Algebra", "Statistics", "Analysis"],
  },
  {
    id: "physics",
    name: "Physics",
    faculty: "Natural Sciences",
    icon: "⚛️",
    color: "from-sky-500 to-cyan-600",
    bgAccent: "bg-sky-500/10",
    examCount: 14,
    studentCount: 1800,
    passRate: 65,
    avgScore: 61,
    difficulty: "Hard",
    topUniversities: ["AAU", "MU", "JU"],
    description: "Classical mechanics, electromagnetism, quantum mechanics and optics.",
    tags: ["Mechanics", "Electromagnetism", "Quantum", "Optics"],
  },

  // ── Agriculture & Veterinary ──────────────────────────────────────────────
  {
    id: "agri",
    name: "Agriculture",
    faculty: "Agriculture & Veterinary",
    icon: "🌾",
    color: "from-lime-600 to-green-700",
    bgAccent: "bg-lime-500/10",
    examCount: 16,
    studentCount: 4400,
    passRate: 80,
    avgScore: 75,
    difficulty: "Medium",
    topUniversities: ["HU", "JU", "BDU", "HARU"],
    description: "Crop science, soil science, agronomy and agricultural economics.",
    tags: ["Crop Science", "Soil Science", "Agronomy", "Irrigation"],
  },
  {
    id: "vetmed",
    name: "Veterinary Medicine",
    faculty: "Agriculture & Veterinary",
    icon: "🐄",
    color: "from-green-600 to-teal-700",
    bgAccent: "bg-green-500/10",
    examCount: 20,
    studentCount: 2600,
    passRate: 73,
    avgScore: 68,
    difficulty: "Hard",
    topUniversities: ["AAU", "HARU", "BDU"],
    description: "Animal health, veterinary pathology, surgery and animal production.",
    tags: ["Animal Health", "Pathology", "Surgery", "Production"],
  },

  // ── Social Sciences & Humanities ─────────────────────────────────────────
  {
    id: "english",
    name: "English Language",
    faculty: "Social Sciences & Humanities",
    icon: "📝",
    color: "from-rose-400 to-pink-500",
    bgAccent: "bg-rose-500/10",
    examCount: 14,
    studentCount: 5600,
    passRate: 84,
    avgScore: 79,
    difficulty: "Easy",
    topUniversities: ["AAU", "JU", "BDU", "HU"],
    description: "Literature, linguistics, academic writing and language skills.",
    tags: ["Literature", "Linguistics", "Writing", "Grammar"],
  },
  {
    id: "psychology",
    name: "Psychology",
    faculty: "Social Sciences & Humanities",
    icon: "🧠",
    color: "from-purple-400 to-violet-500",
    bgAccent: "bg-purple-500/10",
    examCount: 14,
    studentCount: 3400,
    passRate: 81,
    avgScore: 76,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "HU"],
    description: "Developmental, clinical, social and educational psychology.",
    tags: ["Clinical", "Developmental", "Social", "Educational"],
  },
  {
    id: "sociology",
    name: "Sociology",
    faculty: "Social Sciences & Humanities",
    icon: "👥",
    color: "from-orange-400 to-amber-500",
    bgAccent: "bg-orange-500/10",
    examCount: 12,
    studentCount: 3100,
    passRate: 82,
    avgScore: 77,
    difficulty: "Easy",
    topUniversities: ["AAU", "JU", "MU"],
    description: "Social theory, research methods, gender studies and development sociology.",
    tags: ["Social Theory", "Research", "Gender Studies"],
  },
  {
    id: "geography",
    name: "Geography",
    faculty: "Social Sciences & Humanities",
    icon: "🗺️",
    color: "from-teal-400 to-cyan-500",
    bgAccent: "bg-teal-500/10",
    examCount: 12,
    studentCount: 2800,
    passRate: 79,
    avgScore: 74,
    difficulty: "Medium",
    topUniversities: ["AAU", "JU", "BDU"],
    description: "Physical geography, human geography, GIS and cartography.",
    tags: ["Physical Geography", "GIS", "Cartography", "Human Geography"],
  },
  {
    id: "history",
    name: "History",
    faculty: "Social Sciences & Humanities",
    icon: "📜",
    color: "from-amber-400 to-orange-500",
    bgAccent: "bg-amber-500/10",
    examCount: 12,
    studentCount: 2500,
    passRate: 80,
    avgScore: 75,
    difficulty: "Easy",
    topUniversities: ["AAU", "JU", "MU"],
    description: "Ethiopian history, African history, world history and historiography.",
    tags: ["Ethiopian History", "African History", "World History"],
  },
];

export const FACULTIES: Faculty[] = [
  "Engineering & Technology",
  "Health Sciences",
  "Business & Economics",
  "Natural Sciences",
  "Law",
  "Agriculture & Veterinary",
  "Social Sciences & Humanities",
];

export const FACULTY_ICONS: Record<Faculty, string> = {
  "Engineering & Technology": "⚙️",
  "Health Sciences": "🏥",
  "Business & Economics": "📊",
  "Natural Sciences": "🔬",
  "Law": "⚖️",
  "Agriculture & Veterinary": "🌾",
  "Social Sciences & Humanities": "📚",
};

export const FACULTY_COLORS: Record<Faculty, string> = {
  "Engineering & Technology": "from-violet-500 to-indigo-600",
  "Health Sciences": "from-rose-500 to-pink-600",
  "Business & Economics": "from-green-500 to-emerald-600",
  "Natural Sciences": "from-cyan-500 to-blue-600",
  "Law": "from-amber-500 to-yellow-600",
  "Agriculture & Veterinary": "from-lime-500 to-green-600",
  "Social Sciences & Humanities": "from-purple-500 to-violet-600",
};
